# Pinky3 Bridge: Domain 13 -> Domain 25
# Topics from robot (no namespace) are remapped to /pinky3/* namespace
name: pinky3_bridge
from_domain: 13
to_domain: 25
wait_for_publisher: true
topics:
  amcl_pose:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    remap: pinky3/amcl_pose
  odom:
    type: nav_msgs/msg/Odometry
    remap: pinky3/odom
  battery/voltage:
    type: std_msgs/msg/Float32
    remap: pinky3/battery/voltage
  battery/present:
    type: std_msgs/msg/Bool
    remap: pinky3/battery/present
  # LiDAR scan data
  scan:
    type: sensor_msgs/msg/LaserScan
    remap: pinky3/scan
  follow_waypoints/_action/feedback:
    type: nav2_msgs/action/FollowWaypoints_FeedbackMessage
    remap: pinky3/follow_waypoints/_action/feedback
  follow_waypoints/_action/status:
    type: action_msgs/msg/GoalStatusArray
    remap: pinky3/follow_waypoints/_action/status
  navigate_to_pose/_action/feedback:
    type: nav2_msgs/action/NavigateToPose_FeedbackMessage
    remap: pinky3/navigate_to_pose/_action/feedback
  navigate_to_pose/_action/status:
    type: action_msgs/msg/GoalStatusArray
    remap: pinky3/navigate_to_pose/_action/status
