<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>arm_cmd_api_client</name>
  <version>0.1.0</version>
  <description>ROS2 client that calls image analysis server /analyze/arm_cmd API for robot arm integration test</description>
  <maintainer email="emotionalmachine88@gmail.com">GueHoJung88</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <exec_depend>python3-requests</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
